" THIS FILE IS AUTOGENERATED.

if ! exists('g:loaded_vxfold') || ! g:loaded_vxfold
   let g:loaded_vxfold = 1
else
   finish
endif

" <VIMPLUGIN id="vxfold#applications">
   command! VxFoldOrg call vxfold#SetMode('org')
   command! VxFoldTvo call vxfold#SetMode('tvo')
   command! VxFoldViki call vxfold#SetMode('viki')
   command! VxFoldVimWiki call vxfold#SetMode('vimwiki')
" </VIMPLUGIN>
