live_config_reload = true

import = [
  "~/.config/alacritty/theme.toml",
  # "~/.config/alacritty/green.toml",
  "~/.config/alacritty/font.toml",
  # "~/.config/alacritty/font-aquarius.toml",
]

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[scrolling]
history = 0

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t "

[window]
decorations = "none"
startup_mode = "Maximized"
